### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on start

### ISSUE THREAD

**Issue by codlab** [cl3m/multiplatform-compose#7] opened 2022-03-22 19:53 UTC
I'm having an AOB when using the latest version when starting the application on Android (100% reproducible, repository clean)

I'm creating this issue in parallel from testing few things as well

Some contextual information :

- Android version : 12
- Model : Fold 3 / SM-F926B
- commit d9236ff345
- Android Studio 2021.1.1 Patch 2

```
java.lang.ArrayIndexOutOfBoundsException: length=18; index=18
at androidx.compose.ui.graphics.Color.getColorSpace-impl(Color.kt:670)
at androidx.compose.ui.graphics.ColorKt.compositeOver--OWjLjI(Color.kt:559)
at androidx.compose.material.MaterialTextSelectionColorsKt.calculateContrastRatio-nb2GgbA(MaterialTextSelectionColors.kt:199)
at androidx.compose.material.MaterialTextSelectionColorsKt.calculateSelectionBackgroundColor-ysEtTa8(MaterialTextSelectionColors.kt:83)
at androidx.compose.material.MaterialTextSelectionColorsKt.rememberTextSelectionColors(MaterialTextSelectionColors.kt:51)
at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:71)
at com.rouge41.kmm.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:14)
at com.rouge41.kmm.compose.test.ThemeKt.Theme(Theme.kt:20)
at com.rouge41.kmm.compose.test.ContentKt.Content(Content.kt:13)
at com.rouge41.kmm.compose.androidApp.MainActivity$onCreate$1.invoke(MainActivity.kt:26)
at com.rouge41.kmm.compose.androidApp.MainActivity$onCreate$1.invoke(MainActivity.kt:25)
```

Fullstack here : [fullstack.txt](https://github.com/cl3m/multiplatform-compose/files/8327419/fullstack.txt)

**Comment by cl3m** [comment] 2022-03-30 06:46
I could not reproduce with the emulator. Does your PR fix the crash fully ? Can I close the issue ?

**Closed as not planned** 2022-11-18 20:47 UTC
